### ISSUE TITLE
The extension does not work with the new updates for the game, I cannot use the auto filter and the outfit saver didnt work when i first got the extention, May i get the code for it to see if i can fix it?

### ISSUE THREAD

**Issue by The-Coder-2** [Blueyescat/Simple-Dredark-Tools#1]

**Comment by Blueyescat** [comment]
Hello, I noticed that changing outfit doesn't work *only* if you haven't excliptly set the feet color, and just pushed a hotfix update for that (it will take time for Chrome WS to review it). Auto filter wasn't changed in the last update and works as expected, I can tell you are who DM'ed me on Discord then realized it was an user error. Thanks for reporting the bug with outfits if that is the issue what you meant.
